name: odhcp6c

on:
  pull_request:
  push:

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            gcc: /usr/bin/aarch64-linux-gnu-gcc
            packages: gcc-aarch64-linux-gnu
          - arch: arm
            gcc: /usr/bin/arm-linux-gnueabi-gcc
            packages: gcc-arm-linux-gnueabi
          - arch: mips
            gcc: /usr/bin/mips-linux-gnu-gcc
            packages: gcc-mips-linux-gnu
          - arch: x86_64
            gcc: /usr/bin/x86_64-linux-gnu-gcc
            packages: gcc-x86-64-linux-gnu
    outputs:
      size-aarch64-without-libubox: ${{ steps.without_libubox.outputs.size_aarch64 }}
      size-aarch64-with-libubox: ${{ steps.with_libubox.outputs.size_aarch64 }}
      size-arm-without-libubox: ${{ steps.without_libubox.outputs.size_arm }}
      size-arm-with-libubox: ${{ steps.with_libubox.outputs.size_arm }}
      size-mips-without-libubox: ${{ steps.without_libubox.outputs.size_mips }}
      size-mips-with-libubox: ${{ steps.with_libubox.outputs.size_mips }}
      size-x86_64-without-libubox: ${{ steps.without_libubox.outputs.size_x86_64 }}
      size-x86_64-with-libubox: ${{ steps.with_libubox.outputs.size_x86_64 }}
    steps:
      - name: Checkout odhcp6c
        uses: actions/checkout@v5

      - name: Checkout json-c
        uses: actions/checkout@v5
        with:
          repository: json-c/json-c
          path: depends/json-c

      - name: Checkout libubox
        uses: actions/checkout@v5
        with:
          repository: openwrt/libubox
          path: depends/libubox

      - name: Install dependencies
        run: |
          sudo apt install ${{ matrix.packages }}

      - name: Prepare build
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/build

      - name: Build json-c
        working-directory: depends/json-c
        run: |
          cmake \
            -DCMAKE_C_COMPILER=${{ matrix.gcc }} \
            -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/build \
            -DBUILD_SHARED_LIBS=OFF -DDISABLE_EXTRA_LIBS=ON  \
            --install-prefix ${GITHUB_WORKSPACE}/build
          make
          make install

      - name: Build libubox
        working-directory: depends/libubox
        run: |
          cmake \
            -DCMAKE_C_COMPILER=${{ matrix.gcc }} \
            -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/build \
            -DBUILD_LUA=OFF -DBUILD_EXAMPLES=OFF \
            --install-prefix ${GITHUB_WORKSPACE}/build
          make
          make install

      - id: without_libubox
        name: Build odhcp6c (w/o libubox)
        env:
          BUILD_DIR: build/odhcp6c-without-libubox
        run: |
          cmake \
            -DCMAKE_C_COMPILER=${{ matrix.gcc }} \
            -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/build \
            -D USE_LIBUBOX=OFF \
            -B $BUILD_DIR
          make -C $BUILD_DIR
          echo "size_${{ matrix.arch }}=$( find $BUILD_DIR -type f -name odhcp6c -printf '%s' )" >> $GITHUB_OUTPUT

      - id: with_libubox
        name: Build odhcp6c (with libubox)
        env:
          BUILD_DIR: build/odhcp6c-with-libubox
        run: |
          cmake \
            -DCMAKE_C_COMPILER=${{ matrix.gcc }} \
            -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/build \
            -DUSE_LIBUBOX=ON \
            -B $BUILD_DIR
          make -C $BUILD_DIR
          echo "size_${{ matrix.arch }}=$( find $BUILD_DIR -type f -name odhcp6c -printf '%s' )" >> $GITHUB_OUTPUT

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: odhcp6c-${{ matrix.arch }}-binaries
          path: |
            build/odhcp6c-*/odhcp6c
          if-no-files-found: error

  summary:
    name: Sizes
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Sizes summary
        env:
          size_aarch64_without_libubox: ${{needs.build.outputs.size-aarch64-without-libubox}}
          size_aarch64_with_libubox: ${{needs.build.outputs.size-aarch64-with-libubox}}
          size_arm_without_libubox: ${{needs.build.outputs.size-arm-without-libubox}}
          size_arm_with_libubox: ${{needs.build.outputs.size-arm-with-libubox}}
          size_mips_without_libubox: ${{needs.build.outputs.size-mips-without-libubox}}
          size_mips_with_libubox: ${{needs.build.outputs.size-mips-with-libubox}}
          size_x86_64_without_libubox: ${{needs.build.outputs.size-x86_64-without-libubox}}
          size_x86_64_with_libubox: ${{needs.build.outputs.size-x86_64-with-libubox}}
        run: |
          echo "### ${GITHUB_WORKFLOW} sizes :floppy_disk:" >> $GITHUB_STEP_SUMMARY
          echo "| Variant | aarch64 | arm | mips | x86_64 |" >> $GITHUB_STEP_SUMMARY
          echo "| :---: | :---: | :---: | :---: | :---: |" >> $GITHUB_STEP_SUMMARY
          echo "| w/o libubox | ${size_aarch64_without_libubox} | ${size_arm_without_libubox} | ${size_mips_without_libubox} | ${size_x86_64_without_libubox} |" >> $GITHUB_STEP_SUMMARY
          echo "| with libubox | ${size_aarch64_with_libubox} | ${size_arm_with_libubox} | ${size_mips_with_libubox} | ${size_x86_64_with_libubox} |" >> $GITHUB_STEP_SUMMARY
